name: CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: personal-site
  REGISTRY: ledharaujo
  TAG: ${{ github.run_number }}
  FILE: personal-site.yml
  REPO: github.com/leonardo/manifests-swarm.git

jobs:
  build_and_deploy_image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Push docker image
      run: |
        docker login --username ${{ secrets.HUB_USERNAME }} --password ${{ secrets.HUB_TOKEN }}
        docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Update manifest in GitOps repo
      uses: actions/checkout@v4

    - name: Clone GitOps repository
      run: |
        git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@${{ env.REPO }} manifests-swarm
        cd manifests-swarm
        sed -i "s|image: .*/.*:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}|" ${{ env.FILE }}

    - name: Commit manifest update
      run: |
        cd manifests-swarm
        git config user.email "ledharaujo@gmail.com"
        git config user.name "Leonardo Ara√∫jo"
        git add ${{ env.FILE }}
        git commit -m "Update site image to tag ${{ env.TAG }}"
        git push https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/LeonardoHAraujo/manifests-swarm.git HEAD:main
